# Generated by Django 3.2.5 on 2021-07-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='hotspot_image'),
        ),
    ]
