# Generated by Django 3.2.5 on 2021-07-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0008_auto_20210722_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='My Bio', null=True),
        ),
    ]
