# Generated by Django 3.2.5 on 2021-07-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, null=True)),
                ('town', models.CharField(max_length=100, null=True)),
                ('location', models.PositiveBigIntegerField(null=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
        ),
    ]
