# Generated by Django 3.2.5 on 2021-07-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0009_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='hos_image/'),
        ),
        migrations.AddField(
            model_name='police',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='pol_image/'),
        ),
        migrations.AddField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='work_image/'),
        ),
    ]
